name: Snyk Security and License Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'  # Specify your Go version

      # Step 3: Install Snyk CLI
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # Step 4: Authenticate Snyk (this ensures Snyk can run with the provided token)
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Step 5: Run Snyk security test for vulnerabilities
      - name: Run Snyk Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=low

      # Step 6: Check for license issues
      - name: Run Snyk License Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=low --include-licenses
