name: Snyk Incremental Security Scan

on:
  pull_request:
    branches:
      - '*'  # 适用于所有分支

jobs:
  snyk-incremental-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout base branch
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}  # 获取待合入分支的 commit
          fetch-depth: 1  # 只获取基准分支的提交

      # Step 1.1 
      - name: Verify Checked Out Base Branch
        run: |
          echo "Checked out commit:"
          git log -1
        
      # Step 2: Set up Go environment
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Install Snyk CLI
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # Step 4: Authenticate Snyk
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Step 5: Install dependencies on base branch
      - name: Install dependencies on base branch
        run: go mod tidy

      # Step 6: Generate baseline report from the base branch
      - name: Generate Baseline Snyk Report
        working-directory: ${{ github.workspace }}
        run: snyk test --package-manager=gomodules --severity-threshold=low --json > baseline-report.json || true

      # Step 7: Checkout the current PR branch and generate the current report
      - name: Checkout current PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # PR 的最新提交

      - name: Install dependencies on PR branch
        run: go mod tidy

      - name: Generate Current Snyk Report
        run: snyk test --package-manager=gomodules --severity-threshold=low --json > current-report.json || true

      # Step 8: Compare baseline and current reports for new vulnerabilities
      - name: Compare Snyk Reports for New Vulnerabilities
        run: |
          # 使用 jq 提取 baseline 和 current 的漏洞 ID，并对它们进行排序
          baseline_ids=$(jq -r '.vulnerabilities[].id' baseline-report.json | sort | uniq)
          current_ids=$(jq -r '.vulnerabilities[].id' current-report.json | sort | uniq)

          # 查找 current 中存在但 baseline 中不存在的漏洞 ID
          new_vulns=$(comm -13 <(echo "$baseline_ids") <(echo "$current_ids"))

          if [ -n "$new_vulns" ]; then
            echo "New vulnerabilities introduced in this PR:"
            for vuln_id in $new_vulns; do
              # 使用 jq 提取详细信息
              jq --arg id "$vuln_id" '.vulnerabilities[] | select(.id == $id) | "\(.title) (ID: \(.id), Severity: \(.severity))\nDescription: \(.description)\nIntroduced through: \(.from | join(", "))\nMore info: \(.url)\n"' current-report.json
            done
            exit 1  # 如果有新漏洞，让 CI 失败
          else
            echo "No new vulnerabilities introduced in this PR."
          fi
