name: Snyk Incremental Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk-incremental-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code and fetch history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 获取上一次提交

      # Step 2: Set up Go environment
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Install Snyk CLI
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # Step 4: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Install dependencies
        run: go mod tidy

      # Step 5: Generate baseline report from the last commit on main
      - name: Generate Baseline Snyk Report
        run: |
          git checkout origin/main
          snyk test --package-manager=gomodules --severity-threshold=low --json > baseline-report.json

      # Step 6: Generate current report for the PR
      - name: Generate Current Snyk Report
        run: |
          git checkout ${{ github.event.pull_request.head.sha }}
          snyk test --package-manager=gomodules --severity-threshold=low --json > current-report.json

      # Step 7: Compare baseline and current reports for new vulnerabilities
      - name: Compare Snyk Reports for New Vulnerabilities
        run: |
          # 使用 jq 提取 baseline 和 current 的漏洞 ID
          baseline_ids=$(jq -r '.vulnerabilities[].id' baseline-report.json | sort | uniq)
          current_ids=$(jq -r '.vulnerabilities[].id' current-report.json | sort | uniq)

          # 查找 current 中存在但 baseline 中不存在的漏洞 ID
          new_vulns=$(comm -13 <(echo "$baseline_ids") <(echo "$current_ids"))

          if [ -n "$new_vulns" ]; then
            echo "New vulnerabilities introduced in this PR:"
            for vuln_id in $new_vulns; do
              # 使用 jq 提取详细信息
              jq --arg id "$vuln_id" '.vulnerabilities[] | select(.id == $id) | "\(.title) (ID: \(.id), Severity: \(.severity))\nDescription: \(.description)\nIntroduced through: \(.from | join(", "))\nMore info: \(.url)\n"' current-report.json
            done
            exit 1  # 如果有新漏洞，让 CI 失败
          else
            echo "No new vulnerabilities introduced in this PR."
          fi
