name: Snyk Incremental Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current PR branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Step 3: Install Snyk CLI using official action
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # Step 4: Authenticate Snyk
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Step 5: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 6: Detect Dependency Changes in go.sum
      - name: Detect Dependency Changes
        id: diff
        run: |
          git fetch origin main
          # Get only the changes in go.sum and go.mod (new dependencies added or updated)
          git diff origin/main HEAD go.sum | grep '^+[^+]' > dependency-diff.txt
          git diff origin/main HEAD go.mod | grep '^+[^+]' >> dependency-diff.txt
          if [ -s dependency-diff.txt ]; then
            echo "Dependencies changed in go.sum and go.mod"
            cat dependency-diff.txt
          else
            echo "No dependency changes detected."
          fi
        continue-on-error: true

      # Step 7: Show Dependency Changes (for debug purposes)
      - name: Show Dependency Changes
        run: cat dependency-diff.txt

      # Step 8: Run Snyk Test on Incremental Changes
      - name: Run Snyk Test on Incremental Changes
        if: steps.diff.outputs.changed-files == 'go.sum' || success()
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -s dependency-diff.txt ]; then
            echo "Running Snyk test on changed dependencies."
            snyk test --package-manager=gomodules --target-file=dependency-diff.txt --severity-threshold=low
          else
            echo "No dependency changes detected, skipping Snyk test."
          fi
