name: Snyk Incremental Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current PR branch
      - name: Checkout PR code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js to run snyk-pr-diff tool
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'  # 使用与你项目匹配的 Go 版本

      # Step 4: Install snyk-pr-diff tool from GitHub
      - name: Install snyk-pr-diff tool
        run: |
          git clone https://github.com/snyk-playground/cx-tools.git
          cd cx-tools/snyk-pr-diff
          npm install

      # Step 5: Use snyk-pr-diff to detect changed dependencies between the PR branch and main
      - name: Get Dependency Diff
        id: diff
        run: |
          node cx-tools/snyk-pr-diff/get-diff.js origin/main HEAD > dependency-diff.txt
        continue-on-error: true

      # Step 6: Display dependency changes in the PR
      - name: Show Dependency Diff
        run: cat dependency-diff.txt

      # Step 7: Run Snyk Test on the changed dependencies
      - name: Run Snyk Test on Incremental Changes
        if: success() || failure()  # 确保无论差异计算成功与否，都能运行
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          if [ -s dependency-diff.txt ]; then
            snyk test --file=$GITHUB_WORKSPACE/go.sum --severity-threshold=low --only-changed $(cat dependency-diff.txt)
          else
            echo "No dependency changes detected."
          fi
